# Generated by Django 5.0.2 on 2024-03-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Корзина'), ('2', 'Новый'), ('3', 'Подтвержден'), ('4', 'Доставлен'), ('5', 'Отменен')], default='1', max_length=1, verbose_name='Статус заказа'),
        ),
    ]
