# Generated by Django 5.0.2 on 2024-03-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_order_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact',
            new_name='loc_address',
        ),
    ]
