# примеры API-запросов

@baseUrl = http://127.0.0.1:8000



# 
POST {{baseUrl}}/updatecatalog
Content-Type: application/json
Authorization: Token fdefd6d43950704c7044579325f29b5f634463bb

{
  "url": "https://raw.githubusercontent.com/netology-code/pd-diplom/master/data/shop1.yaml"
}
###
# 
POST {{baseUrl}}/user/register
Content-Type: application/json
Authorization: Token fdefd6d43950704c7044579325f29b5f634463bb

{
"first_name":"Djon",
"username":"djon_",
"last_name":"Dilon",
"email":"ao-litvinenko@yandex.ru",
"password":"1234__4843"
}
###
# 
POST {{baseUrl}}/user/login
Content-Type: application/json
Authorization: 5921e755dc1acaf7af5f62953e91f970618f8721

{
"email":"ao-litvinenko@yandex.ru",
"password":"pbkdf2_sha256$720000$48f49itAbNE5skaWejqrIU$j6ku5HyAM+MBeItARjm4eGuFuGmhKu+Vd4B96M0xZ18="
}
###