# примеры API-запросов

@baseUrl = http://127.0.0.1:8000



# 
POST {{baseUrl}}/updatecatalog
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

{
  "url": "https://raw.githubusercontent.com/netology-code/pd-diplom/master/data/shop1.yaml"
}
###
# 
POST {{baseUrl}}/user/register
Content-Type: application/json

{
"first_name":"Dilara",
"username":"Woman",
"last_name":"Dilon",
"email":"ao-litvinenko@yandex.ru",
"password":"1234@fdfd"
}
###
# 
POST {{baseUrl}}/user/login
Content-Type: application/json

{
"email":"ao-litvinenko@yandex.ru",
"password":"1234@fdfd"
}
###
# 
POST {{baseUrl}}/user/register/confirm
Content-Type: application/json

{
"email":"ao-litvinenko@yandex.ru",
"token":"c15450d3a42123bcc31882201010d4b0e74d95e44b33e"

}
###
# 
POST {{baseUrl}}/user-addresses/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

{
  "telephone": "+7-805-546-76-00",
  "city":"kambridge",
  "street":"trafalgar square",
  "house":"7",
  "flat":"305"

}
###

# 
DELETE {{baseUrl}}/user-addresses/11/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

{
 
}
###
# 
GET {{baseUrl}}/user-addresses/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

###

# 
GET {{baseUrl}}/shops/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

###
# 
POST {{baseUrl}}/shops/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

{
  "name":"Mamba_bunba",
  "address":"Мытищи, Станционная, 20",
  "categories": [
    {"name":"Телефон"}, 
    {"name": "Ноутбук_"}
    ] 
}
###
# 
DELETE {{baseUrl}}/shops/16/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

###
# 
PATCH {{baseUrl}}/shops/17/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

{
"state":"False"
}
###
# 
PATCH {{baseUrl}}/shops/17/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

{
  "name":"Mamba_bunba_yes",
  "address":"Мытищи, Колонцова,2",
  "categories": [
    {"name":"Телефон"}, 
    {"name": "Ноутбук_"},
    {"name":"Телевизоры_"}
    ] 
}
###
# 
GET {{baseUrl}}/categories/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

###

# 
GET {{baseUrl}}/products?product_params__value=синий&product_params__parameter__name=Цвет
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

###
# 
GET {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

###
# 
POST {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

{
  "items": [
	{"product_id":  9,	"quantity": 2},
	{"product_id":  11,	"quantity": 5}
]

}

###

# 
PATCH {{baseUrl}}/basket/1/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

{
  "items": [
	{"product_id":  9,	"quantity": 1},
	{"product_id":  11,	"quantity": 1}
]

}

###
# 
DELETE {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

{
  "items": [9,13]
}
###
# 
POST {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token f33fe57297ad729b0163445905e1ba24e34c9d16

{
  "items": [
	{"product_id":  10,	"quantity": 2},
	{"product_id":  11,	"quantity": 5}
]

}
### 
GET {{baseUrl}}/user/orders/
Content-Type: application/json
Authorization: Token f33fe57297ad729b0163445905e1ba24e34c9d16

###

POST {{baseUrl}}/user/orders/
Content-Type: application/json
Authorization: Token f33fe57297ad729b0163445905e1ba24e34c9d16

{
"order_id":8,
"loc_address_id":3
}
###
GET {{baseUrl}}/adminshops/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

###
PATCH {{baseUrl}}/adminshops/8/
Content-Type: application/json
Authorization: Token 4f88de02ff8d92c8ea1b08c1ecd6836b9655db30

{
  "order_id":8,
  "status":5
  
}
###